### ISSUE TITLE
Transactional event store question

### ISSUE THREAD

**Issue by n3vrax** [prooph/pdo-event-store#127]
Hi there,

I'm looking forward to use these nice libraries
I'm currently checking out the event store and pdo adapters documentation and source code and I came across the transactional aspect of the stores
My question is why the postgres adapter is implemented as a transactional store only. I see that mysql store has transaction handling internally. Why not making it implement the transactional store too?

I'm asking this because I have the following situation: I want to create a CQRS application without event sourcing, but using domain events that are also stored in the same db.
I'm using doctrine repositories for storing my aggregates and I'm currently handling the transaction session by myself, by using a command decorator that uses the doctrine transaction handling. I also want to use the mysql event store with a pdo connection to the same db as doctrine.

Now, if I use the EventPublisher without the TransactionManager, I quess the events will be published before committing, which is not desirable. And the transaction manager can't be used with the mysql event store, am I right?

Do you have any suggestions on handling this use case. I want to use as much as I can from your packages without major overwriting. I was thinking about:
 
 - create a custom mysql event store that implements the transactional store, and use the transaction manager from the bus bridge to wrap the entire command in the event store transaction, basically eliminating the need to handle the transaction by myself, through doctrine

 - manually handling the transaction(maybe using a custom command plugin) and somehow storing the recorded events and delay their publishing until the commit is succesful(any suggestions on how to accomplish would be great)

Sorry for the lengthy text, hope I made myself clear. I'm hoping someone had faced already this problem and can help me with some suggestions...

Thanks in advance !

**Comment by prolic** [comment]
A normal appendTo/create operation on the MySQLEventStore is already handled in transaction internally, so you can be sure all or nothing is persisted. So you may not need transaction support maybe?

The MySQLEventStore can't implement the TransactionalEventStore interface, because MySQL will do an implicit commit once you create or alter a tabl (see https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html). However you can disable transaction handling (see https://github.com/prooph/pdo-event-store/blob/master/src/MySqlEventStore.php#L78) and handle transactions yourself (assumed you don't use aggregate stream strategy and don't create new tables within this transaction).

The TransactionManager can't be used with the MySQLEventStore, correct.

The EventPublisher can be used without the TransactionManager but will then publish events after they were applied to the EventStore, it will not obey manual transaction handling. If you want to have an EventPublisher handling your manual transaction handling, go for it, it has only 100 lines of code then you can copy/paste/adjust for your needs.

**Comment by n3vrax** [comment]
Thanks for your quick reply

I'll be using the MysqlSimpleStreamStrategy, so tables will be created manually only once. But I get the mysql limitation.

Your suggestion is really helpful, I'll try to leverage the command and even store generated events and create an EventPublisher of my own. I'll try the following, and write it down here so others might find it useful:
- create a command bus plugin that will manage doctrine transactions
- create an event publisher that will hook into the event-store `create` and `appendTo` events and store the generated events internally
- the event publisher will also hook into the command bus finalize event, and on successful commit it will dispatch to event bus the previously stored domain events

It sounds good in theory
Thanks again and have a nice evening!
