### ISSUE TITLE
Floats in events are serialized as integers

### ISSUE THREAD

**Issue by enumag** [prooph/pdo-event-store#154]
When I have a float value in an event without decimals (for example `1.0`) it is saved to the EventStore as simply `1`. Because of this when the event is later retrieved from the EventStore and deserialized, the information that the number was a float is lost - it becomes an integer.

If this is intended for Prooph then just close this issue. If you want to fix it then it's easy to do so using `JSON_PRESERVE_ZERO_FRACTION`. I can send a pull request for this.

----

Another thing to consider is checking if the json serialization didn't produce any errors using the `json_last_error()` function.

Personally I'm using [`Nette\Utils\Json`](https://api.nette.org/2.4/source-Utils.Json.php.html#25-47) in my project which also adds `JSON_UNESCAPED_UNICODE` and `JSON_UNESCAPED_SLASHES` flags handles some other issues. There is something similar although less advanced in [Enqueue](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Util/JSON.php#L45-L57) library which uses just `JSON_UNESCAPED_UNICODE` and `json_last_error()`.

I assume you don't want to add a dependency to another library so I won't send a pull request for this.

**Comment by prolic** [comment]
We can check for json_last_error() and use additional flags, wanna submit a PR?

**Comment by enumag** [comment]
Only if it would be integration of an existing library. I don't have time to copy the logic to prooph and write all necessary tests.

**Comment by basz** [comment]
## summerizing

### JSON_PRESERVE_ZERO_FRACTION
definitely an issue. A value as float(-1.0) will become int(1) without 

### JSON_UNESCAPED_UNICODE
If I understand this correctly. "က" is encoded as "\u1000" without the flag en "က" with. json_decode works regardless. So adding this flag we would go from  \u1000 notation which should work in any table/column to "က" for which the correct collation should be set. Seems to me adding it (now) will be more problematic then leaving it off. Not sure. see: https://3v4l.org/FKj8I

### JSON_UNESCAPED_SLASHES
Same as JSON_UNESCAPED_UNICODE. It will change the way payloads are stored. See. https://3v4l.org/5cROr

I worry (just a bit) that changing json encoding midway might lead to problems with ~half of your events later on. Especially when someone is using the payloads directly.

### json_last_error()
Want this one for sure. I think better save then sorry is a good lead here. For example. Feeding a circular reference will happily encode and only the backend will trigger an insert error because "" is not valid  json. When someone is using the message bus, a circular reference will never happen as that has it's own serialisation checks.

## solution:
A library is not an option and since prooph/common is deprecated that's not a place for serialisation either. How about a small JsonUtil inside event-store, so we have this in a single and thus consistent place? We wouldn't want to be fixing this again and again...

**Comment by fritz-gerneth** [comment]
> definitely an issue. A value as float(-1.0) will become int(1) without

Minor typo, should be `int(-1)`. 
Personally I don't see any issue on this though. JSON representation is an internal format only. So output format only matters. But this is up to your events anyway. What is the benefit of storing the fraction? 

Storing the fraction does not the decoded result. Neither does adding an explicit cast to a float.
```
php > echo json_decode(json_encode(-1.0, JSON_PRESERVE_ZERO_FRACTION));
-1
php > echo (float) json_decode(json_encode(-1.0, JSON_PRESERVE_ZERO_FRACTION));
-1
```
On the event side you should result anyway and not relay on some automatic json casting. 
```
public function getValue(): float
{
        return (float) $this->payload['myValue'];
}
```

**Comment by ramondelafuente** [comment]
When working with the `MariaDbSingleStreamStrategy`, we're having trouble storing unicode characters in the payload. As stated, the string "က" is encoded as "\u1000", which then gets escaped to "\\u1000" when storing the event. This triggers an error in the "`CHECK (`payload` IS NOT NULL AND JSON_VALID(`payload`))" that exists on the table definition, leading to a very confusing "Duplicate key" error.

Adding the `JSON_UNESCAPED_UNICODE` flag solves the problem; and since the table is created with the definition from the PersistenceStrategy itsself we can be sure that the table does support this.

It's not exactly on-topic so I'll make a new issue if required.

**Comment by enumag** [comment]
I don't think this will be fixed in Prooph 7 because of BC and Prooph 8 will only be event store so it's not really related (maybe as an util class). But it's surely something to be mentioned in the docs at least.

@prolic What is the current status btw? I didn't really follow prooph since the big announcement but there doesn't seem to be anything happening in the awesomeness repo either.

**Comment by prolic** [comment]
@enumag most of my free time currently goes into this: https://github.com/prooph/event-store-client
